In [43]:
import pandas as pd

### Load and explore PM2.5 dataset

In [44]:
df = pd.read_csv('here.csv')
df.head()

,sensor_name,latitude,longitude,timestamp,pm25
0,ELDA-LACY,38.454722,-0.803333,"{'utc': '2016-12-07T12:00:00Z', 'local': '2016...",9.0
1,ELDA-LACY,38.454722,-0.803333,"{'utc': '2016-12-07T14:00:00Z', 'local': '2016...",8.0
2,ELDA-LACY,38.454722,-0.803333,"{'utc': '2016-12-07T15:00:00Z', 'local': '2016...",8.0
3,ELDA-LACY,38.454722,-0.803333,"{'utc': '2016-12-07T16:00:00Z', 'local': '2016...",11.0
4,ELDA-LACY,38.454722,-0.803333,"{'utc': '2016-12-07T17:00:00Z', 'local': '2016...",15.0

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1129395 entries, 0 to 1129394
Data columns (total 5 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   sensor_name  1129395 non-null  object
 1   latitude     1129395 non-null  float64
 2   longitude    1129395 non-null  float64
 3   timestamp    1129395 non-null  object
 4   pm25         1129395 non-null  float64
dtypes: float64(3), object(2)
memory usage: 43.1+ MB

In [46]:
df['timestamp'].unique()[0]

"{'utc': '2016-12-07T12:00:00Z', 'local': '2016-12-07T13:00:00+01:00'}"

- **Split `timestamp` into `utc` and `local` time features**

In [47]:
import ast

# Parse the timestamp column (string representation of dict) and extract utc and local
df['timestamp'] = df['timestamp'].apply(ast.literal_eval)
df['utc'] = pd.to_datetime(df['timestamp'].apply(lambda x: x['utc']))
df['local'] = pd.to_datetime(df['timestamp'].apply(lambda x: x['local']))

# Drop the original timestamp column
df = df.drop('timestamp', axis=1)

# Display the result
df.head()

C:\Users\djame\AppData\Local\Temp\ipykernel_13796\2653024797.py:6: FutureWarning: In a future version of pandas, parsing datetimes with mixed time zones will raise an error unless `utc=True`. Please specify `utc=True` to opt in to the new behaviour and silence this warning. To create a `Series` with mixed offsets and `object` dtype, please use `apply` and `datetime.datetime.strptime`
  df['local'] = pd.to_datetime(df['timestamp'].apply(lambda x: x['local']))

,sensor_name,latitude,longitude,pm25,utc,local
0,ELDA-LACY,38.454722,-0.803333,9.0,2016-12-07 12:00:00+00:00,2016-12-07 13:00:00+01:00
1,ELDA-LACY,38.454722,-0.803333,8.0,2016-12-07 14:00:00+00:00,2016-12-07 15:00:00+01:00
2,ELDA-LACY,38.454722,-0.803333,8.0,2016-12-07 15:00:00+00:00,2016-12-07 16:00:00+01:00
3,ELDA-LACY,38.454722,-0.803333,11.0,2016-12-07 16:00:00+00:00,2016-12-07 17:00:00+01:00
4,ELDA-LACY,38.454722,-0.803333,15.0,2016-12-07 17:00:00+00:00,2016-12-07 18:00:00+01:00

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1129395 entries, 0 to 1129394
Data columns (total 6 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   sensor_name  1129395 non-null  object
 1   latitude     1129395 non-null  float64
 2   longitude    1129395 non-null  float64
 3   pm25         1129395 non-null  float64
 4   utc          1129395 non-null  datetime64[ns, UTC]
 5   local        1129395 non-null  object
dtypes: datetime64[ns, UTC](1), float64(3), object(2)
memory usage: 51.7+ MB

In [49]:
sorted_df = df.sort_values(by='utc')
sorted_df.head()

,sensor_name,latitude,longitude,pm25,utc,local
85163,VALÈNCIA-PISTA DE SILLA,39.456111,-0.375833,3.0,2016-11-21 19:00:00+00:00,2016-11-21 20:00:00+01:00
1017034,ALGAR DE PALÀNCIA,39.782222,-0.359167,1.0,2016-11-21 19:00:00+00:00,2016-11-21 20:00:00+01:00
1067034,SAGUNT CEA,39.634167,-0.265833,1.0,2016-11-21 19:00:00+00:00,2016-11-21 20:00:00+01:00
68163,VALÈNCIA-POLITÈCNIC,39.480300,-0.336400,2.0,2016-11-21 19:00:00+00:00,2016-11-21 20:00:00+01:00
145010,SAGUNT CEA,39.634167,-0.265833,1.0,2016-11-21 19:00:00+00:00,2016-11-21 20:00:00+01:00

In [50]:
sorted_df.tail()

,sensor_name,latitude,longitude,pm25,utc,local
593716,Barcelona - Camp d'en Grassot,41.401828,2.166360,23.2,2026-04-16 05:00:00+00:00,2026-04-16 07:00:00+02:00
578270,Passeig de Fabra i Puig,41.430123,2.179321,14.3,2026-04-16 05:00:00+00:00,2026-04-16 07:00:00+02:00
567792,Barcelona - Porta - Can Dragó,41.431949,2.180739,23.3,2026-04-16 05:00:00+00:00,2026-04-16 07:00:00+02:00
583937,Polinya,41.557686,2.158661,9.7,2026-04-16 05:00:00+00:00,2026-04-16 07:00:00+02:00
593386,Sant Francesc,41.477833,2.087572,12.9,2026-04-16 05:00:00+00:00,2026-04-16 07:00:00+02:00

In [51]:
# Extract just the date part (YYYY-MM-DD) from utc column
sorted_df['utc_date'] = pd.to_datetime(sorted_df['utc']).dt.date

# Get unique dates
unique_dates = sorted_df[['utc_date']].drop_duplicates()
unique_dates.columns = ['date']

# Save to CSV
unique_dates.to_csv('unique_dates.csv', index=False)

print(f"Found {len(unique_dates)} unique dates")
print(unique_dates.head())

Found 3100 unique dates
              date
85163   2016-11-21
162011  2016-11-22
145014  2016-11-23
145018  2016-11-25
145024  2016-11-26

### Load and explore GEE dataset

In [52]:
gee = pd.read_csv('gee_features_daily.csv')
gee.tail()

,date,datetime_utc,id,lat,lon,temperature_celsius,pressure_mb,wind_u,wind_v,NO2,CO,O3,AOD
164203,2026-04-06,2026-04-06 00:00:00,105,38.057300,-1.204700,16.151273,998.739201,-1.016339,0.227157,0.000081,0.030380,0.149699,0.0635
164204,2026-04-06,2026-04-06 00:00:00,106,37.974500,-1.232100,16.031563,1000.354618,-1.057110,-0.167496,0.000083,0.030047,0.150451,0.0620
164205,2026-04-06,2026-04-06 00:00:00,107,38.057373,-1.204813,16.151273,998.739201,-1.016339,0.227157,0.000081,0.030380,0.149699,0.0635
164206,2026-04-06,2026-04-06 00:00:00,108,37.970100,-1.127700,15.901273,1005.128784,-1.220766,-0.413671,0.000077,0.030002,0.150418,0.0500
164207,2026-04-06,2026-04-06 00:00:00,109,37.992300,-1.145900,15.901273,1005.128784,-1.220766,-0.413671,0.000077,0.030002,0.150418,0.0500

### Check where does the GEE dataset's date ends.

In [60]:
gee['date'].sort_values(ascending=False).head()

164207    2026-04-06
164149    2026-04-06
164140    2026-04-06
164141    2026-04-06
164142    2026-04-06
Name: date, dtype: object

- Check `gee` values for a specific `lat` value.

In [53]:
import numpy as np
# Use tolerance-based comparison instead
result = gee[np.isclose(gee['lat'], 38.057300, atol=1e-6)]
print(f"\nRows with tolerance-based comparison:")
result.tail()

Rows with tolerance-based comparison:

,date,datetime_utc,id,lat,lon,temperature_celsius,pressure_mb,wind_u,wind_v,NO2,CO,O3,AOD
163925,2026-04-03,2026-04-03 00:00:00,107,38.057373,-1.204813,14.722916,996.663770,0.169507,-0.611101,0.000076,0.032510,0.172907,0.0785
164017,2026-04-04,2026-04-04 00:00:00,105,38.057300,-1.204700,15.113154,999.761509,-0.202812,0.742929,0.000093,0.031586,0.157822,0.0395
164019,2026-04-04,2026-04-04 00:00:00,107,38.057373,-1.204813,15.113154,999.761509,-0.202812,0.742929,0.000093,0.031586,0.157822,0.0395
164203,2026-04-06,2026-04-06 00:00:00,105,38.057300,-1.204700,16.151273,998.739201,-1.016339,0.227157,0.000081,0.030380,0.149699,0.0635
164205,2026-04-06,2026-04-06 00:00:00,107,38.057373,-1.204813,16.151273,998.739201,-1.016339,0.227157,0.000081,0.030380,0.149699,0.0635

In [54]:
result.shape

(3408, 13)

### Merge PM2.5 and GEE datasets

In [55]:
sorted_df.columns

Index(['sensor_name', 'latitude', 'longitude', 'pm25', 'utc', 'local',
       'utc_date'],
      dtype='object')

- Create `utc_date` feature

In [56]:
sorted_df['utc_date'] = sorted_df['utc'].dt.date.astype(str)
pm25_df = sorted_df.copy()

pm25_df.head()

,sensor_name,latitude,longitude,pm25,utc,local,utc_date
85163,VALÈNCIA-PISTA DE SILLA,39.456111,-0.375833,3.0,2016-11-21 19:00:00+00:00,2016-11-21 20:00:00+01:00,2016-11-21
1017034,ALGAR DE PALÀNCIA,39.782222,-0.359167,1.0,2016-11-21 19:00:00+00:00,2016-11-21 20:00:00+01:00,2016-11-21
1067034,SAGUNT CEA,39.634167,-0.265833,1.0,2016-11-21 19:00:00+00:00,2016-11-21 20:00:00+01:00,2016-11-21
68163,VALÈNCIA-POLITÈCNIC,39.480300,-0.336400,2.0,2016-11-21 19:00:00+00:00,2016-11-21 20:00:00+01:00,2016-11-21
145010,SAGUNT CEA,39.634167,-0.265833,1.0,2016-11-21 19:00:00+00:00,2016-11-21 20:00:00+01:00,2016-11-21

- merge the datasets on `latitude`, `longitude`, `utc_date`

In [57]:
gee['date'].value_counts()

date
2026-02-21    100
2025-10-04    100
2025-10-01    100
2025-09-03    100
2025-08-30    100
             ...
2025-04-03      2
2020-01-20      1
2025-02-25      1
2024-01-19      1
2026-02-10      1
Name: count, Length: 2393, dtype: int64

In [58]:
# Prepare sorted_df for merge: convert utc_date to string
sorted_df_merge = sorted_df.copy()
sorted_df_merge['date'] = sorted_df_merge['utc_date'].astype(str)

# Merge on date, latitude (lat), and longitude (lon)
merged_df = sorted_df_merge.merge(
    gee,
    on=['date', 'lat', 'lon'],
    how='inner'
)

print(f"Merged dataset shape: {merged_df.shape}")
print(f"PM2.5 rows: {len(sorted_df_merge)}, GEE rows: {len(gee)}, Merged rows: {len(merged_df)}")
print(f"\nColumns: {list(merged_df.columns)}")
print(f"\nFirst few rows:")
merged_df.head()

KeyError: 'lat'

In [61]:
gee.shape, pm25_df.shape

((164208, 13), (1129395, 7))

**Size difference:**
- In PM2.5 dataset, each records have multiple rows for the same date (at different time).

- GEE dataset has one row for each (lat, lon, date).

In [62]:
pm25_df[['utc_date', 'latitude', 'longitude']].drop_duplicates().shape

(66029, 3)

In [65]:
temp = pd.read_csv('pm25_final.csv')
temp.head()

,sensor_name,latitude,longitude,timestamp,pm25
0,ELDA-LACY,38.454722,-0.803333,"{'utc': '2016-12-07T12:00:00Z', 'local': '2016...",9.0
1,ELDA-LACY,38.454722,-0.803333,"{'utc': '2016-12-07T14:00:00Z', 'local': '2016...",8.0
2,ELDA-LACY,38.454722,-0.803333,"{'utc': '2016-12-07T15:00:00Z', 'local': '2016...",8.0
3,ELDA-LACY,38.454722,-0.803333,"{'utc': '2016-12-07T16:00:00Z', 'local': '2016...",11.0
4,ELDA-LACY,38.454722,-0.803333,"{'utc': '2016-12-07T17:00:00Z', 'local': '2016...",15.0

In [66]:
temp.shape

(216436, 5)

In [67]:
import ast

# Parse the timestamp column (string representation of dict) and extract utc and local
temp['timestamp'] = temp['timestamp'].apply(ast.literal_eval)
temp['utc'] = pd.to_datetime(temp['timestamp'].apply(lambda x: x['utc']))
temp['local'] = pd.to_datetime(temp['timestamp'].apply(lambda x: x['local']))

# Drop the original timestamp column
temp = temp.drop('timestamp', axis=1)

# Display the result
temp.head()

C:\Users\djame\AppData\Local\Temp\ipykernel_13796\1230218195.py:6: FutureWarning: In a future version of pandas, parsing datetimes with mixed time zones will raise an error unless `utc=True`. Please specify `utc=True` to opt in to the new behaviour and silence this warning. To create a `Series` with mixed offsets and `object` dtype, please use `apply` and `datetime.datetime.strptime`
  temp['local'] = pd.to_datetime(temp['timestamp'].apply(lambda x: x['local']))

,sensor_name,latitude,longitude,pm25,utc,local
0,ELDA-LACY,38.454722,-0.803333,9.0,2016-12-07 12:00:00+00:00,2016-12-07 13:00:00+01:00
1,ELDA-LACY,38.454722,-0.803333,8.0,2016-12-07 14:00:00+00:00,2016-12-07 15:00:00+01:00
2,ELDA-LACY,38.454722,-0.803333,8.0,2016-12-07 15:00:00+00:00,2016-12-07 16:00:00+01:00
3,ELDA-LACY,38.454722,-0.803333,11.0,2016-12-07 16:00:00+00:00,2016-12-07 17:00:00+01:00
4,ELDA-LACY,38.454722,-0.803333,15.0,2016-12-07 17:00:00+00:00,2016-12-07 18:00:00+01:00

In [68]:
temp.shape

(216436, 6)

In [83]:
print (f'shape before dropping duplicates: {pm25_df.shape}')
pm25_df = pm25_df.drop_duplicates()
print (f'shape after dropping duplicates: {pm25_df.shape}')

shape before dropping duplicates: (1129395, 7)
shape after dropping duplicates: (1015087, 7)

In [88]:
print (f'shape before dropping duplicates: {temp.shape}')
temp = temp.drop_duplicates()
print (f'shape after dropping duplicates: {temp.shape}')

shape before dropping duplicates: (216436, 6)
shape after dropping duplicates: (197078, 6)

In [93]:
temp_keys = temp[['latitude', 'longitude', 'utc']].drop_duplicates()

merged = pm25_df.merge(temp_keys, 
                       on=['latitude', 'longitude', 'utc'], 
                       how='left', 
                       indicator=True)

pm25_only = merged[merged['_merge'] == 'left_only'].drop('_merge', axis=1)
pm25_both = merged[merged['_merge'] == 'both'].drop('_merge', axis=1)

In [94]:
pm25_only.shape[0] + pm25_both.shape[0] == pm25_df.shape[0]

True

In [95]:
import pandas as pd
import glob
import ast

LOCATIONS = [
    (36.1706, -5.3976, "Casablanca"), (36.7571, -4.5753, "Rabat"), (36.8422, -2.4612, "Tanger"),
    (37.16565, -3.60008, "Granada"), (37.60308, -0.97538, "Málaga"), (37.6936, -1.06464, "Motril"),
    (37.99359, -1.14472, "Vera"), (37.99102, -0.69008, "Mojacar"), (38.6394, -0.87238, "Almería"),
    (39.4776, -0.414, "Benidorm"), (39.7087, -0.2781, "Valencia"), (39.9986, -0.0731, "Castellón"),
    (39.769, 3.29, "Palma"), (40.00921, 3.8562, "Barcelona"), (39.26097, 9.13651, "Palermo"),
    (41.474, 2.0948, "Girona"), (41.11609, 1.19202, "Tarragona"), (43.41652, 5.22228, "Marseille"),
    (43.56248, 7.00722, "Antibes"), (42.67133, 9.43451, "Corsica"), (34.28899, 8.7616, "Tunis"),
    (35.28204, -2.94925, "Melilla"), (31.8747, -7.8907, "Laayoune"), (36.75649, 3.03772, "Algiers")
]

all_files = glob.glob("*.csv")
# Use the locations list to filter out unrelated CSV files like "here.csv" or "unique_dates.csv"
region_csvs = [f for f in all_files if any(region.replace(" ", "_") in f for lat, lon, region in LOCATIONS)]

final_data = []
print("--- Concatenating regional files ---")
for csv_file in region_csvs:
    try:
        df_region = pd.read_csv(csv_file)
        final_data.append(df_region)
        print(f"Loaded {len(df_region)} records from {csv_file}")
    except Exception as e:
        print(f"Error loading {csv_file}: {e}")

if final_data:
    combined_df = pd.concat(final_data, ignore_index=True)
    print(f"\nTotal hourly records combined: {len(combined_df)}")
    
    # Parse the string representation of dictionary to get UTC correctly
    print("Formatting timestamps and aggregating...")
    combined_df['timestamp'] = combined_df['timestamp'].apply(ast.literal_eval)
    combined_df['date'] = pd.to_datetime(combined_df['timestamp'].apply(lambda x: x['utc'])).dt.date
    
    daily_df = combined_df.groupby(['date', 'latitude', 'longitude']).agg({
        'pm25': 'mean',
        'sensor_name': 'first'
    }).reset_index()
    
    print(f"Total daily aggregated records: {len(daily_df)}")
    
    output_file = "pm25_1800days_final.csv"
    daily_df.to_csv(output_file, index=False)
    print(f"Saved aggregated data successfully to {output_file}")
else:
    print("No regional data found.")

--- Concatenating regional files ---
Loaded 17000 records from Algiers.csv
Loaded 52926 records from Almería.csv
Loaded 72936 records from Antibes.csv
Loaded 15237 records from Barcelona.csv
Loaded 165437 records from Benidorm.csv
Loaded 224273 records from Casablanca.csv
Loaded 123915 records from Castellón.csv
Loaded 30000 records from Corsica.csv
Loaded 86523 records from Girona.csv
Loaded 32821 records from Granada.csv
Loaded 249130 records from Marseille.csv
Loaded 31367 records from Melilla.csv
Loaded 17000 records from Mojacar.csv
Loaded 59182 records from Motril.csv
Loaded 59182 records from Málaga.csv
Loaded 27299 records from Palermo.csv
Loaded 33887 records from Rabat.csv
Loaded 50000 records from Tanger.csv
Loaded 54112 records from Tarragona.csv
Loaded 1685 records from Tunis.csv
Loaded 68000 records from Valencia.csv
Loaded 53023 records from Vera.csv

Total hourly records combined: 1524935
Formatting timestamps and aggregating...
Total daily aggregated records: 88041
Saved aggregated data successfully to pm25_1800days_final.csv

In [96]:
df = pd.read_csv('pm25_1800days_final.csv')
df.head()

         date   latitude  longitude  pm25              sensor_name
0  2016-11-21  38.788056  -0.697222   4.0                ONTINYENT
1  2016-11-21  39.456111  -0.375833   3.0  VALÈNCIA-PISTA DE SILLA
2  2016-11-21  39.480300  -0.336400   2.0      VALÈNCIA-POLITÈCNIC
3  2016-11-21  39.481100  -0.408300   5.0  VALÈNCIA - MOLÍ DEL SOL
4  2016-11-21  39.481111  -0.447222   2.0          QUART DE POBLET

In [97]:
df.shape

(88041, 5)

In [98]:
df.duplicated().sum()

np.int64(0)

In [99]:
gee.duplicated().sum()

np.int64(0)

In [102]:
gee.tail()

,date,datetime_utc,id,lat,lon,temperature_celsius,pressure_mb,wind_u,wind_v,NO2,CO,O3,AOD
164203,2026-04-06,2026-04-06 00:00:00,105,38.057300,-1.204700,16.151273,998.739201,-1.016339,0.227157,0.000081,0.030380,0.149699,0.0635
164204,2026-04-06,2026-04-06 00:00:00,106,37.974500,-1.232100,16.031563,1000.354618,-1.057110,-0.167496,0.000083,0.030047,0.150451,0.0620
164205,2026-04-06,2026-04-06 00:00:00,107,38.057373,-1.204813,16.151273,998.739201,-1.016339,0.227157,0.000081,0.030380,0.149699,0.0635
164206,2026-04-06,2026-04-06 00:00:00,108,37.970100,-1.127700,15.901273,1005.128784,-1.220766,-0.413671,0.000077,0.030002,0.150418,0.0500
164207,2026-04-06,2026-04-06 00:00:00,109,37.992300,-1.145900,15.901273,1005.128784,-1.220766,-0.413671,0.000077,0.030002,0.150418,0.0500

In [101]:
gee.shape

(164208, 13)

- Exploring combined PM2.5 with GEE

In [2]:
import pandas as pd

com_df = pd.read_csv('combined_gee_pm25.csv')
com_df.head()

,date,datetime_utc,id,latitude,longitude,temperature_celsius,pressure_mb,wind_u,wind_v,NO2,CO,O3,AOD,pm25,sensor_name
0,2016-11-25,2016-11-25 00:00:00,1,38.788056,-0.697222,6.493180,946.288660,0.230240,0.735303,NaN,NaN,NaN,0.1110,2.750000,ONTINYENT
1,2016-11-25,2016-11-25 00:00:00,36,39.945278,-0.056389,9.251236,993.626994,0.783218,-0.592618,NaN,NaN,NaN,0.0220,11.666667,ALMASSORA-C. P. OCHANDO
2,2016-11-30,2016-11-30 00:00:00,35,40.051944,-0.189722,10.044782,981.911432,-2.211047,-1.568971,NaN,NaN,NaN,0.2380,2.400000,ALCORA
3,2016-11-30,2016-11-30 00:00:00,37,40.062222,0.072778,12.299584,1008.794766,-3.236886,-2.804465,NaN,NaN,NaN,0.2480,2.600000,BENICASSIM
4,2016-12-02,2016-12-02 00:00:00,1,38.788056,-0.697222,9.350630,953.114180,0.953454,0.293060,NaN,NaN,NaN,0.0755,2.750000,ONTINYENT

In [ ]:
com_df.shape

(41718, 15)

How many unique locations are there?

In [4]:
com_df.groupby(['latitude', 'longitude']).size().reset_index(name='counts').shape

(98, 3)

In [ ]:
land_df = pd.read_csv('dataset_with_landuse.csv')
land_df.head()

,date,datetime_utc,id,latitude,longitude,temperature_celsius,pressure_mb,wind_u,wind_v,NO2,CO,O3,AOD,pm25,sensor_name,building_density,road_density_km,industrial_presence,green_space_fraction
0,2016-11-25,2016-11-25 00:00:00,1,38.788056,-0.697222,6.493180,946.288660,0.230240,0.735303,NaN,NaN,NaN,0.111000,2.750000,ONTINYENT,88,94.835390,0,4
1,2016-11-25,2016-11-25 00:00:00,36,39.945278,-0.056389,9.251236,993.626994,0.783218,-0.592618,NaN,NaN,NaN,0.022000,11.666667,ALMASSORA-C. P. OCHANDO,779,329.395812,5,467
2,2016-11-30,2016-11-30 00:00:00,35,40.051944,-0.189722,10.044782,981.911432,-2.211047,-1.568971,NaN,NaN,NaN,0.238000,2.400000,ALCORA,22,171.888897,2,3
3,2016-11-30,2016-11-30 00:00:00,37,40.062222,0.072778,12.299584,1008.794766,-3.236886,-2.804465,NaN,NaN,NaN,0.248000,2.600000,BENICASSIM,1275,294.935993,4,143
4,2016-12-02,2016-12-02 00:00:00,1,38.788056,-0.697222,9.350630,953.114180,0.953454,0.293060,NaN,NaN,NaN,0.075500,2.750000,ONTINYENT,88,94.835390,0,4
5,2016-12-02,2016-12-02 00:00:00,6,39.456111,-0.375833,11.741255,1012.708763,0.569380,-0.217011,NaN,NaN,NaN,0.074667,10.600000,VALÈNCIA-PISTA DE SILLA,11678,1135.345397,3,19006
6,2016-12-02,2016-12-02 00:00:00,5,39.480300,-0.336400,11.741255,1012.708763,0.569380,-0.217011,NaN,NaN,NaN,0.074667,13.400000,VALÈNCIA-POLITÈCNIC,8493,739.947698,4,13951
7,2016-12-02,2016-12-02 00:00:00,7,39.481100,-0.408300,11.186079,1005.518763,0.742882,-0.273163,NaN,NaN,NaN,0.065667,24.200000,VALÈNCIA - MOLÍ DEL SOL,7433,1012.635090,6,10644
8,2016-12-02,2016-12-02 00:00:00,12,39.481111,-0.447222,11.186079,1005.518763,0.742882,-0.273163,NaN,NaN,NaN,0.065667,12.800000,QUART DE POBLET,4875,544.756718,18,779
9,2016-12-02,2016-12-02 00:00:00,11,39.634167,-0.265833,11.006636,1000.260013,0.530073,-0.049327,NaN,NaN,NaN,0.167000,12.250000,SAGUNT CEA,38,196.101150,28,197
10,2016-12-02,2016-12-02 00:00:00,102,39.705278,-0.336667,9.225549,967.947096,0.494551,-0.294933,NaN,NaN,NaN,0.095500,6.200000,ALBALAT DELS TARONGERS,93,222.363555,2,2
11,2016-12-02,2016-12-02 00:00:00,101,39.782222,-0.359167,9.225549,967.947096,0.494551,-0.294933,NaN,NaN,NaN,0.095500,7.800000,ALGAR DE PALÀNCIA,35,186.386843,4,11
12,2016-12-02,2016-12-02 00:00:00,38,39.892222,-0.065000,11.667769,1006.780430,0.601647,0.021392,NaN,NaN,NaN,0.113500,8.666667,BURRIANA,3144,300.889527,13,60
13,2016-12-02,2016-12-02 00:00:00,36,39.945278,-0.056389,11.065637,1000.462513,0.543135,-0.195893,NaN,NaN,NaN,0.074500,9.333333,ALMASSORA-C. P. OCHANDO,779,329.395812,5,467
14,2016-12-02,2016-12-02 00:00:00,35,40.051944,-0.189722,9.058394,970.977930,0.574263,-0.443167,NaN,NaN,NaN,0.055000,5.333333,ALCORA,22,171.888897,2,3
15,2016-12-02,2016-12-02 00:00:00,37,40.062222,0.072778,11.278934,997.458346,0.672448,-0.052847,NaN,NaN,NaN,0.073667,4.000000,BENICASSIM,1275,294.935993,4,143
16,2016-12-03,2016-12-03 00:00:00,1,38.788056,-0.697222,9.090952,948.776672,-0.578416,0.426319,NaN,NaN,NaN,0.127000,10.500000,ONTINYENT,88,94.835390,0,4
17,2016-12-03,2016-12-03 00:00:00,6,39.456111,-0.375833,11.500783,1008.658755,-0.162034,-0.934358,NaN,NaN,NaN,0.250500,11.500000,VALÈNCIA-PISTA DE SILLA,11678,1135.345397,3,19006
18,2016-12-03,2016-12-03 00:00:00,5,39.480300,-0.336400,11.500783,1008.658755,-0.162034,-0.934358,NaN,NaN,NaN,0.250500,15.500000,VALÈNCIA-POLITÈCNIC,8493,739.947698,4,13951
19,2016-12-03,2016-12-03 00:00:00,7,39.481100,-0.408300,10.760630,1001.489588,-0.188564,-0.719922,NaN,NaN,NaN,0.262000,25.000000,VALÈNCIA - MOLÍ DEL SOL,7433,1012.635090,6,10644

In [7]:
land_df.shape

(41718, 19)

In [ ]:
import pandas as pd

# Load your original PM2.5 dataset
df = pd.read_csv('pm25.csv')  # Replace with your actual filename

# Extract unique coordinates
unique_coords = df[['latitude', 'longitude']].drop_duplicates()

# Save to CSV
unique_coords.to_csv('unique_coordinates.csv', index=False)

print(f"Saved {len(unique_coords)} unique coordinates")
print(unique_coords.head())

Saved 133 unique coordinates
    latitude  longitude
0  38.788056  -0.697222
1  39.456111  -0.375833
2  39.480300  -0.336400
3  39.481100  -0.408300
4  39.481111  -0.447222

In [20]:
df['date'] = pd.to_datetime(df['date'])

unique_dates = df['date'].drop_duplicates()

# Save to CSV
unique_dates.to_csv('unique_dates.csv', index=False)

print(f"Saved {len(unique_dates)} unique dates")

Saved 3131 unique dates